# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    # - name: Distribute app via Firebase App Distribution
    #   env:
    #       firebaseToken: ${{ secrets.FIREBASE_TOKEN }}
    #       firebaseGroups: ${{ secrets.FIREBASE_GROUPS }}
    #       firebaseAppId: ${{ secrets.FIREBASE_APP_ID }}
    #       notes: ${{ github.event.head_commit.message }}
    #   run: |
    #     yarn global add firebase-tools
    #     export PATH="$(yarn global bin):$PATH"
    #     firebase \
    #       appdistribution:distribute android/app/build/outputs/apk/release/app-release.apk \
    #       --app $firebaseAppId \
    #       --release-notes "$notes" \
    #       --groups "$firebaseGroups" \
    #       --token "$firebaseToken"
